# Generated by Django 3.0.5 on 2020-09-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=100)),
                ('leader', models.BooleanField()),
                ('title', models.CharField(default='', max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionName', models.CharField(default='', editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('prerequisite', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('instructor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tye.Instructor')),
                ('session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tye.Session')),
            ],
        ),
    ]
