# Generated by Django 3.0.5 on 2020-10-27 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('speaker', models.CharField(default=False, max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='event_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.BooleanField()),
                ('title', models.CharField(default='', max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='instructor_pics')),
                ('active_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionName', models.CharField(max_length=50)),
                ('active_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('prerequisite', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='course_pics')),
                ('instructor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tye.Instructor')),
                ('session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tye.Session')),
            ],
        ),
    ]
