# Generated by Django 3.0.5 on 2020-10-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
