# Generated by Django 3.0.5 on 2020-09-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tye', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(),
        ),
    ]
