# Generated by Django 3.0.5 on 2020-09-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tye', '0005_auto_20200926_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
