# Generated by Django 3.0.5 on 2020-09-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tye', '0006_auto_20200928_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='status',
            new_name='active_status',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='status',
            new_name='active_status',
        ),
    ]
