# Generated by Django 3.0.5 on 2020-10-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tye', '0008_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='parent',
        ),
    ]
