# Generated by Django 3.0.5 on 2020-10-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_order_ordercourse_transactoion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercourse',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
