# Generated by Django 3.0.5 on 2020-10-28 21:19

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_ordercourse_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercourse',
            name='student',
            field=models.ForeignKey(default=builtins.max, on_delete=django.db.models.deletion.CASCADE, to='enroll.Student'),
            preserve_default=False,
        ),
    ]
