# Generated by Django 3.0.5 on 2020-10-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_remove_ordercourse_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactoion',
        ),
    ]
