# Generated by Django 3.0.5 on 2020-10-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_auto_20201029_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercourse',
            name='user',
        ),
    ]
